#! /bin/sh
#
# Usage: strip-comments FILE...
# Strips C/C++ style comments from FILE(s).
# Be carefull: the files are substituted in place.
#
# A lot of room left for improvements:
# - No quote recognizing (!!)
# - No intensive testing done

sed -i -se '
# Remove single line comments (C style)
s|/\*.*\*/||g

# Remove single line comments (C++ style)
# This is quite dangerous, so it is disable by default
#s|//.*||

# Remove multiline comments (C style)
/\/\*.*/,/.*\*\//d' $@
