<?php
/* vim: set expandtab shiftwidth=4 softtabstop=4 tabstop=4: */

/**
 * @package TIP
 * @subpackage Module
 */

/** HTML_QuickForm PEAR package */
require_once 'HTML/QuickForm.php';

/**
 * Form generator
 *
 * Manages all the forms generated by the TIP system using the QuickForm PEAR
 * package.
 *
 * @final
 * @package TIP
 * @subpackage Module
 */
class TIP_Form extends TIP_Module
{
    /**#@+ @access private */

    var $_block = null;
    var $_form = null;
    var $_defaults = null;


    function TIP_Form()
    {
        $this->TIP_Module();
        $this->on_process =& $this->callback('_onProcess');
    }

    function& _addEnum(&$field)
    {
        $id = $field['id'];
        $label = $this->_block->getLocale($id . '_label');
        $items = array_flip($field['choices']);
        array_walk($items, array(&$this->_block, 'localize'), array($id . '_', '_label'));

        // On lot of available choices, use a select menu
        if (count($field['choices']) > 3) {
            return $this->_form->addElement('select', $id, $label, $items);
        }

        // On few available choices, use radio button
        $group = array();
        foreach ($items as $i_value => $i_label) {
            $item =& $this->_form->createElement('radio', $id, $label, $i_label, $i_value);
            $group[] =& $item;
        }
        return $this->_form->addElement('group', $id, $label, $group, ' &nbsp; ', false);
    }

    function& _addSet(&$field)
    {
        $id = $field['id'];
        $label = $this->_block->getLocale($id . '_label');
        $items = array_flip($field['choices']);
        array_walk($items, array(&$this->_block, 'localize'), $id . '_label');

        $group = array();
        foreach ($items as $i_value => $i_label) {
            $item =& $this->_form->createElement('advcheckbox', $id, $label, $i_label);
            $group[] =& $item;
        }

        return $this->_form->addElement('group', $id, $label, $group, ' &nbsp; ');
    }

    function& _addGeneric(&$field)
    {
        $id = $field['id'];
        $label = $this->_block->getLocale($id . '_label');

        if (strpos(strtolower($id), 'password') !== false) {
            $element =& $this->_form->addElement('password', $id, $label);

            $reid = 're' . $id;
            $relabel = $this->_block->getLocale($reid . '_label');
            $slave =& $this->_form->addElement('password', $reid, $relabel);
            if ($field['length'] > 0) {
                $slave->setMaxLength($field['length']);
            }

            $this->_addRule($reid, 'required');
            $message = $this->getLocale('repeat');
            $this->_form->addRule(array($reid, $id), $message, 'compare', null);
            return $element;
        }

        return $this->_form->addElement('text', $id, $label);
    }

    function _addRule($element, $type, $format = '')
    {
        $message = $this->getLocale($type);
        $this->_form->addRule($element, $message, $type, $format);
    }

    function _onProcess($row)
    {
        $primary_key = $this->_block->data->primary_key;
        $this->_block->data->forceFieldType($row);

        $id = @$row[$primary_key];
        if (is_null($id)) {
            // Put operation
            $this->_block->data->putRow($row);
        } else {
            // Update operation
            $this->_block->data->updateRow($id, $row);
        }
    }

    /**#@-*/


    /**#@+ @access public */

    /**
     * Process callback
     *
     * Function to call while processing the data. It takes one argument:
     * an associative array of validated values.
     *
     * By default, if the value with the primary field key is not found in the
     * array this callback will add a new row to the $data object of the binded
     * block or will update an existing row if the primary key field is found.
     *
     * @var TIP_Callback
     */
    var $on_process = null;


    /**
     * Create a generic form
     *
     * This is the main function of the form management: it creates a form
     * for $block by inspecting the field structure of its $data object.
     * The structure is obtained from $data by calling TIP_Data::getFields()
     * and passing true as $detailed argument.
     *
     * The default values of the fields can be optionally passed in the $row
     * associative array.
     *
     * This form is only created as data structure: no echo operations are
     * performed in this step.
     *
     * @param TIP_Block &$block The requesting block
     * @param array     &$row   The default values
     * @return bool true on success or false on errors
     */
    function make(&$block, $row = null)
    {
        $this->_block =& $block;
        $this->_form =& new HTML_QuickForm($block->data->path);
        $this->_defaults =& $row;

        $application =& $GLOBALS[TIP_MAIN_MODULE];
        $fields =& $block->data->getFields();
        $primary_key = $block->data->primary_key;

        $this->_form->removeAttribute('name'); // XHTML compliance

        $header = $block->getLocale(is_null($row) ? 'add_header' : 'edit_header');
        $this->_form->addElement('header', 'PageHeader', $header);
        $this->_form->addElement('hidden', 'module', $this->_block->getName());
        $this->_form->addElement('hidden', 'action', $application->keys['ACTION']);
        if (array_key_exists($primary_key, $row)) {
            $this->_form->addElement('hidden', $primary_key, $row[$primary_key]);
        }

        foreach (array_keys($fields) as $id) {
            if (substr($id, 0, 1) == '_') {
                continue;
            }

            $field =& $fields[$id];
            if ($field['automatic']) {
                continue;
            }

            $method = '_add' . @$field['subtype'];
            if (! method_exists($this, $method)) {
                $method = '_addGeneric';
            }

            $element =& $this->$method($field);
            if (is_null($element)) {
                continue;
            }

            $maxlength = $field['length'];
            if ($maxlength > 0) {
                if (method_exists($element, 'setMaxLength')) {
                    $element->setMaxLength($maxlength);
                }
                $this->_addRule($id, 'maxlength', $field['length']);
            }

            if (is_numeric($field['default'])) {
                $this->_addRule($id, 'numeric');
            }

            if ($field['info'] == 'required') {
                $this->_addRule($id, 'required');
            }
        }

        $this->_form->applyFilter('__ALL__', 'trim');
        return true;
    }

    /**
     * Process the form
     *
     * Processing a form means executing all the tasks the form is born for:
     * validating, storing the result and freezing the form. Only the render
     * process is left over to the TIP_Form::render() method. This is done
     * to allow the rendering of the form when you need it, usually in a
     * callback of the application.
     *
     * If the validation fails, the render process will reshow the form not
     * frozed (ready for input) showing the failed validation using the
     * HTML_QuickForm methods.
     *
     * If the validation is succesful, the storing of the data will be done
     * by calling to the TIP_Form::$on_process callback and the form will
     * be reshown throught TIP_Form::view().
     *
     * @return bool true on success or false on errors
     */
    function process()
    {
        if ($this->_form->validate()) {
            if (@TIP::getSession('form.to_process')) {
                $this->_form->process(array(&$this->on_process, 'go'));
                TIP::setSession('form.to_process', null);
                TIP::info('I_DONE');
            }

            return $this->view(TIP::buildUrl('index.php'));
        } else {
            TIP::setSession('form.to_process', true);

            // Add reset and submit buttons
            $group[] = $this->_form->createElement('reset', null, $this->getLocale('reset'));
            $group[] = $this->_form->createElement('submit', null, $this->getLocale('submit'));
            $this->_form->addElement('group', 'buttons', null, $group);

            if (is_array($this->_defaults)) {
                // Set the default values from the given row
                $defaults =& $this->_defaults;
            } else {
                // Set the default values with the defaults from TIP_Data
                $fields =& $this->_block->data->getFields();
                $defaults = array_map(create_function('&$f', 'return $f["default"];'), $fields);
            }

            $this->_form->setDefaults($defaults);
        }

        return true;
    }

    /**
     * Prepare the form to be viewed
     *
     * Simply adds a 'Back' button and freezes the form. The link the 'Back'
     * button must point to is defined with the $referer argument: if not
     * specified, the referer of the server ($_SERVER['HTTP_REFERER']) will be
     * used instead.
     *
     * @param string $referer The link where to turn back
     * @return bool true on success or false on errors
     */
    function view($referer = null)
    {
        if (is_null($referer) && is_null($referer = $_SERVER['HTTP_REFERER'])) {
            $referer = TIP::buildUrl('index.php');
        }

        // Add the 'Back' button
        $element =& $this->_form->addElement('link', 'back', null, $referer);
        $element->setText($this->getLocale('back'));
        $element->setAttribute('class', 'command');

        $this->_form->freeze();
        return true;
    }

    /**
     * Render the form
     *
     * This is the final step of the TIP_Form module: the rendering.
     * An HTML representation of the form in the current state (frozen or not)
     * is output.
     *
     * @return bool true on success or false on errors
     */
    function render()
    {
        $this->_form->display();
        return true;
    }

    /**#@-*/
}

return 'TIP_Form';

?>
