<?php
/* vim: set expandtab shiftwidth=4 softtabstop=4 tabstop=4 foldmethod=marker: */

/**
 * TIP_Advertisement definition file
 * @package TIP
 * @subpackage Module
 */

/**
 * Advertisement module
 *
 * @package TIP
 * @subpackage Module
 */
class TIP_Advertisement extends TIP_Content
{
    //{{{ Properties

    /**
     * The field owning the expiration time
     * @var string
     */
    protected $expiration_field = '_expiration';

    /**
     * The default expiration time
     * @var string
     */
    protected $expiration = '+2 month';

    //}}}
    //{{{ Construction/destruction

    /**
     * Check the options
     *
     * Overridable static method that checks $options for missing or invalid
     * values and eventually corrects its content.
     *
     * @param  array &$options Properties values
     * @return bool            true on success or false on error
     */
    static protected function checkOptions(&$options)
    {
        if (!parent::checkOptions($options)) {
            return false;
        }

        isset($options['browsable_fields']) || $options['browsable_fields'] = array(
            TIP_PRIVILEGE_NONE    => array('group'),
            TIP_PRIVILEGE_TRUSTED => array('_user'),
            TIP_PRIVILEGE_ADMIN   => array('_check', '_public', '__ALL__')
        );
        return true;
    }

    /**
     * Constructor
     *
     * Initializes a TIP_Advertisement instance.
     *
     * $options inherits the TIP_Content properties, and add the following:
     * - $options['expiration_field']: the field owning the expiration time
     * - $options['expiration']:       the default expiration time
     *
     * @param array $options Properties values
     */
    protected function __construct($options)
    {
        parent::__construct($options);
    }

    //}}}
    //{{{ Callbacks

    /**
     * 'on_row' callback for TIP_Data_View
     *
     * Adds the following calculated fields to every data row:
     * - 'EXPIRED': true if the advertisement is expired
     *
     * @param  array &$row The row as generated by TIP_Data_View
     * @return bool        always true
     */
    public function _onDataRow(&$row)
    {
        $row['EXPIRED'] = TIP::getTimestamp($row[$this->expiration_field], 'iso8601') > time();
        return true;
    }

    /**
     * 'add' callback
     *
     * Overrides the default callback setting the initial expiration value.
     *
     * @param  array &$row The data row to add
     * @return bool        true on success, false on errors
     */
    public function _onAdd(&$row)
    {
        isset($this->expiration_field) &&
            empty($row[$this->expiration_field]) &&
            $row[$this->expiration_field] = TIP::formatDate('datetime_iso8601', strtotime($this->expiration));
        return parent::_onAdd($row);
    }


    public function _onCheck(&$old_row)
    {
        $row['_check'] = 'yes';
        $row['_check_on'] = TIP::formatDate('datetime_iso8601');
        $row['_check_by'] = TIP::getUserId();

        if (!$this->data->updateRow($row, $old_row)) {
            TIP::notifyError('update');
            TIP::warning("unable to update a row ($id)");
            return false;
        }

        $signaled = $old_row['_user'];
        $user = TIP_Application::getSharedModule('user');

        // Update statistics of the signaling user
        if (!is_null($user)) {
            $user->increment('_checked');
        }

        // Update statistics of the signaled user
        if ($signaled && !is_null($user) &&
            !is_null($view = $user->startDataView($user->getProperty('data')->rowFilter($signaled)))) {
            $row = $view->current();
            $user->endView();
            if (!is_null($row)) {
                $old_row = $row;
                ++ $row['_own_checked'];
                $user->getProperty('data')->updateRow($row, $old_row);
            }
        }

        return true;
    }

    public function _onLegalize(&$old_row)
    {
        $row['_check'] = 'no';
        if (!$this->data->updateRow($row, $old_row)) {
            TIP::notifyError('update');
            TIP::warning("unable to update a row ($id)");
            return false;
        }

        $signaling = $old_row['_check_by'];
        $signaled = $old_row['_user'];
        $user = TIP_Application::getSharedModule('user');

        // Update statistics of the signaling user
        if ($signaling && !is_null($user) &&
            !is_null($view = $user->startDataView($user->getProperty('data')->rowFilter($signaling)))) {
            $row = $view->current();
            $user->endView();
            if (!is_null($row)) {
                $old_row = $row;
                ++ $row['_unchecked'];
                $user->getProperty('data')->updateRow($row, $old_row);
            }
        }

        // Update statistics of the signaled user
        if ($signaled && !is_null($user) &&
            !is_null($view = $user->startDataView($user->getProperty('data')->rowFilter($signaled)))) {
            $row = $view->current();
            $user->endView();
            if (!is_null($row)) {
                $old_row = $row;
                ++ $row['_own_unchecked'];
                $user->getProperty('data')->updateRow($row, $old_row);
            }
        }

        return true;
    }

    public function _onRefresh(&$old_row)
    {
        if (isset($this->expiration_field, $this->expiration) && ($expiration = strtotime($this->expiration)) !== false) {
            $row[$this->expiration_field] = TIP::formatDate('datetime_iso8601', $expiration);
            if (!$this->data->updateRow($row, $old_row)) {
                TIP::notifyError('update');
                TIP::warning("unable to update a row ($id)");
                return false;
            }
        }

        return true;
    }

    //}}}
    //{{{ Actions

    /**
     * Perform a browse action
     *
     * Overrides the default browse action, filtering out the expired
     * advertisements and sorting the result in reverse creation order.
     *
     * @param  string|array $filter The filter to use
     * @return bool                 true on success or false on errors
     */
    protected function actionBrowse($filter)
    {
        is_array($filter) && $filter = implode(' AND ', $filter);

        // If not administrator, filter out the expired advertisement and
        // update the browsed rows counter
        $update_browsed_rows = $this->privilege < TIP_PRIVILEGE_ADMIN;
        if ($update_browsed_rows) {
            $filter .= $this->data->addFilter('AND', $this->expiration_field, TIP::formatDate('datetime_iso8601'), '>');
        }

        // Force a descending order on the creation field
        $filter .= $this->data->order($this->creation_field, TIP_DESCENDING);

        return parent::actionBrowse($filter, $update_browsed_rows);
    }

    protected function actionCheck($id, $options = null)
    {
        isset($options) || $options = array(
            'command'    => 'check',
            'buttons'    => TIP_FORM_BUTTON_OK|TIP_FORM_BUTTON_CANCEL,
            'on_process' => array(&$this, '_onCheck')
        );
        return !is_null($this->form(TIP_FORM_ACTION_CUSTOM, $id, $options));
    }

    protected function actionLegalize($id, $options = null)
    {
        isset($options) || $options = array(
            'command'    => 'legalize',
            'buttons'    => TIP_FORM_BUTTON_OK|TIP_FORM_BUTTON_CANCEL,
            'on_process' => array(&$this, '_onLegalize')
        );
        return !is_null($this->form(TIP_FORM_ACTION_CUSTOM, $id, $options));
    }

    protected function actionRefresh($id, $options = null)
    {
        isset($options) || $options = array(
            'command'    => 'refresh',
            'buttons'    => TIP_FORM_BUTTON_OK|TIP_FORM_BUTTON_CANCEL,
            'on_process' => array(&$this, '_onRefresh')
        );
        return !is_null($this->form(TIP_FORM_ACTION_CUSTOM, $id, $options));
    }


    protected function runAdminAction($action)
    {
        switch ($action) {

        case 'legalize':
            return
                !is_null($id = $this->fromGetOrPost()) &&
                $this->actionLegalize($id);

        case 'refresh':
            return
                !is_null($id = $this->fromGetOrPost()) &&
                $this->actionRefresh($id);
        }

        return parent::runAdminAction($action);
    }

    protected function runTrustedAction($action)
    {
        switch ($action) {

        case 'check':
            return
                !is_null($id = $this->fromGetOrPost()) &&
                $this->isNotOwner($id) &&
                $this->actionCheck($id);

        case 'refresh':
            return
                !is_null($id = $this->fromGetOrPost()) &&
                $this->isOwner($id) &&
                $this->actionRefresh($id);
        }

        return parent::runTrustedAction($action);
    }

    //}}}
}
?>
