<?php
/* vim: set expandtab shiftwidth=4 softtabstop=4 tabstop=4 foldmethod=marker: */

/**
 * TIP_Sponsor definition file
 * @package TIP
 * @subpackage Module
 */

/**
 * Sponsor module
 *
 * Provides a basic implementation for a sponsor module.
 *
 * @package TIP
 * @subpackage Module
 */
class TIP_Sponsor extends TIP_Content
{
    //{{{ Internal properties

    /**
     * Row of the current showed sponsor
     * @var array
     * @internal
     */
    private $_row = null;

    /**
     * Old content of $_row
     * @var array
     * @internal
     */
    private $_old_row = null;

    //}}}
    //{{{ Constructor/destructor

    /**
     * Constructor
     *
     * Initializes a TIP_Sponsor instance.
     *
     * @param array $options Properties values
     */
    protected function __construct($options)
    {
        parent::__construct($options);
    }

    protected function postConstructor()
    {
        parent::postConstructor();

        $filter = $this->data->order('_count') . ' LIMIT 1';
        if (!is_null($view = $this->startDataView($filter))) {
            $this->_row = $this->_old_row = $view->current();
            // Increment _count_field
            ++ $this->_row['_count'];
        }
    }

    /**
     * Destructor
     * Updates the current sponsor statistics
     */
    function __destruct()
    {
        if (is_array($this->_row)) {
            $this->data->updateRow($this->_row, $this->_old_row);
            $this->endView();
        }
    }

    //}}}
    //{{{ Callbacks

    /**
     * 'on_row' callback for TIP_Data_View
     *
     * Adds the following calculated fields to every data row:
     * - 'COUNT': the difference between counts and submitted counts
     * - 'HITS':  the difference between hits and submitted hits
     *
     * @param  array &$row The row as generated by TIP_Data_View
     * @return bool        always true
     */
    public function _onDataRow(&$row)
    {
        $row['COUNT'] = $row['_count'] - $row['_submitted_count'];
        $row['HITS'] = $row['_hits'] - $row['_submitted_hits'];
        return true;
    }

    //}}}
}
?>
